### ISSUE TITLE
During data preprocessing, an error occurred when running mu.pp.neighbors()

### ISSUE THREAD

**Issue by watermelon-flower** [ChaozhongLiu/TREASMO#1]
Hi TREASMO team,
paper looked really cool! So I wanted to try and run on some of my own data and the code provided:
rna = ad.read_h5ad('data/HSPC_Muon_RNA.h5ad')
atac = ad.read_h5ad('data/HSPC_Muon_ATAC.h5ad')
mdata = mu.MuData({"rna": rna, "atac": atac})
mu.pp.intersect_obs(mdata)
mdata.shape
**mu.pp.neighbors(mdata, n_neighbors=20)**
mu.tl.umap(mdata)
however, I get the following error message:
Traceback (most recent call last):
  File "D:\PYTHON\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 78, in <module>
  File "D:\PYCHARM\TREASMO\XUNI\lib\site-packages\muon\_core\preproc.py", line 623, in neighbors
    mdata.obsp[conns_key] = connectivities
  File "D:\PYCHARM\TREASMO\XUNI\lib\site-packages\anndata\_core\aligned_mapping.py", line 181, in __setitem__
    value = self._validate_value(value, key)
  File "D:\PYCHARM\TREASMO\XUNI\lib\site-packages\anndata\_core\aligned_mapping.py", line 68, in _validate_value
    if self.parent.shape[axis] != dim_len(val, i):
  File "D:\PYTHON\lib\functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "D:\PYCHARM\TREASMO\XUNI\lib\site-packages\anndata\utils.py", line 69, in dim_len
    return x.shape[axis]
**AttributeError: 'tuple' object has no attribute 'shape'**
can you tell me how can i solve it? Thank you!!!

**Comment by ChaozhongLiu** [comment]
Hi there,
Thanks for you interests in TREASMO!
From the error message, the problem seems to be with [Muon](https://github.com/scverse/muon?tab=readme-ov-file),  and it seems that they don't have clear error message on this.
I suppose it could be due to version changes or your data.
  
Could you please try:
1. what is the output of ``mdata.shape``? Does it contain any cell?
2. Switch to Muon version as the one my experiment used: ``0.1.5``

**Comment by watermelon-flower** [comment]
> 您好，感谢您对TREASMO的关注！从错误消息来看，问题似乎出[在 Muon](https://github.com/scverse/muon?tab=readme-ov-file) 上，而且他们似乎没有明确的错误消息。我想这可能是由于版本更改或您的数据造成的。
> 
> 你能试试吗？
> 
> 1. 的输出是什么？它包含任何细胞吗？`mdata.shape`
> 2. 切换到我的实验使用的 Muon 版本：`0.1.5`

I'm going to try to modify it based on your suggestion, thanks！！！
